{
    "name": "Helpdesk Enhanced - Ticket SLA",
    "summary": "Add SLA to the tickets for Helpdesk Management.",
    "version": "14.0.1.0.0",
    "author": "Monema S.r.l.",
    "maintainer": "Monema S.r.l.",
    "contributors": ["Andrea Bettarini <bettarini@monema.it>"],
    "website": "https://github.com/OCA/helpdesk",
    "license": "Other OSI approved licence",
    "category": "After-Sales",
    "application": False,
    "depends": ["helpdesk_mgmt", "helpdesk_mgmt_sla"],
    "data": [
        "security/ir.model.access.csv",
        "views/action_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_sla_views.xml",
        "views/menu.xml",
    ],
}
